### PR TITLE
port to Meteor 0.6.5

### PR DESCRIPTION
**Pull request by lalomartins**
This version works for me with the new build system in Meteor 0.6.5; I'm using it in an active project that's going into production soon.

Warning, it's **NOT** backwards-compatible. I don't think it's possible ATM to write a version that works both with the old and new APIs, unless you want to play with version detection.

### CODE REVIEW

**Comment by lalomartins** [comment]
forgot to mention, I wrote this the night 0.6.5 was released, so it's been tested for some time already, and it's stable for me.

**Comment by vraptor75011** [comment]
Tried it with meteor 0.6.5.1 and 0.6.5, does not seem to work. Same error as @aknuds1

**Comment by lalomartins** [comment]
A backtrace doesn't really help very much, sorry, without some context. What were you trying to do, what template were you trying to render, or was this at startup? This backtrace shows that an error happened and Meteor couldn't figure out how to report it. Without context, it's meaningless.

**Comment by aknuds1** [comment]
@lalomartins Will try to provide more context when time permits.

**Comment by vraptor75011** [comment]
@lalomartins Happens at startup with a unique file body.blade containing only a div statement.

**Comment by lalomartins** [comment]
thanks, I'll see if I can reproduce.

**Comment by vraptor75011** [comment]
Had to modify the package.js file located in meteor/tools/xxxxxxxx/tools line 1248 

``` javascript

                compileStep.addJavaScript({ sourcePath: compileStep.inputPath,
                                            path: relPath,
                                            data: data.toString('utf8') });
```

and use the @chroz fork in smart.json

``` javascript


{
  "packages": {
    "blade": {
        "git": "https://github.com/chroz/meteor-blade.git"
    },
    "bootstrap-3": {},
    "accounts-ui-bootstrap-3": {}
  }
}
```

**Comment by bminer** [comment]
Hey, guys.  Just checking in.  Is this pull request ready to go?  Has it been thoroughly tested with `isolates`, `constant` blocks, etc.???

I'd like to spend some time culling through this (and perhaps merging this PR in the near future).

Thanks!

**Comment by lalomartins** [comment]
Hi Blake,

in my project, I did have isolates and constants, and it all worked.

However, other people (see above) tried my branch, and it didn't work for them. So I might be missing something from my setup that made it work.

At the moment I had to remove blade from the project, so I don't really have a living test case anymore, nor a strong motivation to pursue development :-/

**Pull request closed without merging**
